# Generated by Django 5.0.6 on 2024-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
